### ISSUE TITLE
Platform-specific shaders

### ISSUE THREAD

**Issue by impworks** [impworks/corund#8]
The way shaders are built differs across platforms. Therefore, we need the following structure:

* Main library contains just code
* Shaders are built specifically for each platform in a separate satellite assembly
* The user references the main library and one appropriate satellite
* When using `GameEngine.Init`, the satellite is registered as shader implementation source

Two assemblies are currently set up: `Corund.Effects.WP8` and `Corund.Effects.Android`. The actual shader code resides in the `Corund.Effects` folder.

The trouble is that PCL does not support `ResourceManager.GetObject` to get raw byte arrays. Only `GetString` is supported. Therefore, the built `*.xnb` must be encoded and decoded via Base64.

**Comment by ForNeVeR** [comment]
Have you tried to access the shader without `ResourceManager` as an embedded resource via e.g. `typeof(BlurShader).GetTypeInfo().Assembly.GetManifestResourceStream("blur.xnb")`? I think it should work even in PCL.

**Comment by impworks** [comment]
Will give it a go.

**Comment by impworks** [comment]
Worked for WP8, will probably work for other platforms too!
